# Generated by Django 5.2.16 on 2026-07-15 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='origin',
            old_name='origin_name',
            new_name='origin',
        ),
    ]
