# Generated by Django 5.2.16 on 2026-07-15 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0002_rename_origin_name_origin_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_code', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='origin',
            name='appointment_code',
        ),
        migrations.RemoveField(
            model_name='origin',
            name='name',
        ),
        migrations.AddField(
            model_name='origin',
            name='participant',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='origin.participant'),
            preserve_default=False,
        ),
    ]
