# Generated by Django 5.2.16 on 2026-07-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0003_participant_remove_origin_appointment_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='appointment_code',
            field=models.CharField(max_length=5),
        ),
    ]
