# Generated by Django 5.2.16 on 2026-07-16 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0004_alter_participant_appointment_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='origin',
            name='participant',
        ),
        migrations.AddField(
            model_name='origin',
            name='appointment_code',
            field=models.CharField(default='99999', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='origin',
            name='name',
            field=models.CharField(default='name', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
