# Generated by Django 5.2.16 on 2026-07-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0005_remove_origin_participant_origin_appointment_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='origin',
            name='appointment_code',
            field=models.CharField(max_length=6),
        ),
    ]
