# Generated by Django 5.2.16 on 2026-07-21 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_appointment_appointment_code'),
        ('origin', '0006_alter_origin_appointment_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='origin',
            name='appointment_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origins', to='appointment.appointment', to_field='appointment_code'),
        ),
    ]
