# Generated by Django 5.2.16 on 2026-07-22 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0008_alter_origin_appointment_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='origin',
            old_name='appointment_code',
            new_name='appointment',
        ),
    ]
