# Generated by Django 5.2.16 on 2026-07-21 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_appointment_appointment_code'),
        ('station', '0002_seed_stations'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_num', models.IntegerField()),
                ('station_name', models.CharField(max_length=50)),
                ('lines', models.JSONField()),
                ('average_time', models.IntegerField()),
                ('is_recommended', models.BooleanField(default=False)),
                ('participants', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_stations', to='appointment.appointment')),
            ],
            options={
                'ordering': ['place_num'],
            },
        ),
    ]
