# Generated by Django 5.2.16 on 2026-07-15 23:48

import appointment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField()),
                ('appointment_code', models.CharField(default=appointment.models.generate_appointment_code, editable=False, max_length=12, unique=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', '진행중'), ('COMPLETED', '완료')], default='IN_PROGRESS', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
