# Generated by Django 5.2.16 on 2026-07-16 08:02

import appointment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_code',
            field=models.CharField(default=appointment.models.generate_appointment_code, editable=False, max_length=6, unique=True),
        ),
    ]
